from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 359)
        MainWindow.setFixedSize(340, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 151, 191))
        self.groupBox.setObjectName("groupBox")
        self.dur_cb = QtWidgets.QComboBox(self.groupBox)
        self.dur_cb.setGeometry(QtCore.QRect(10, 50, 121, 26))
        self.dur_cb.setObjectName("dur_cb")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.dur_cb.addItem("")
        self.measure_line = QtWidgets.QLineEdit(self.groupBox)
        self.measure_line.setGeometry(QtCore.QRect(10, 100, 113, 21))
        self.measure_line.setObjectName("measure_line")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_6.setObjectName("label_6")
        self.num_of_tacts_sb = QtWidgets.QSpinBox(self.groupBox)
        self.num_of_tacts_sb.setGeometry(QtCore.QRect(10, 150, 121, 24))
        self.num_of_tacts_sb.setObjectName("num_of_tacts_sb")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 0, 151, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 70, 101, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.div_parts_sb = QtWidgets.QSpinBox(self.groupBox_3)
        self.div_parts_sb.setGeometry(QtCore.QRect(10, 40, 61, 24))
        self.div_parts_sb.setMinimum(2)
        self.div_parts_sb.setMaximum(4)
        self.div_parts_sb.setObjectName("div_parts_sb")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.label_4.setObjectName("label_4")
        self.div_perc_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.div_perc_sb.setGeometry(QtCore.QRect(10, 50, 101, 24))
        self.div_perc_sb.setMaximum(100)
        self.div_perc_sb.setObjectName("div_perc_sb")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 190, 151, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_5.setObjectName("label_5")
        self.rests_perc_sb = QtWidgets.QSpinBox(self.groupBox_4)
        self.rests_perc_sb.setGeometry(QtCore.QRect(10, 50, 91, 24))
        self.rests_perc_sb.setMaximum(100)
        self.rests_perc_sb.setObjectName("rests_perc_sb")
        self.Generate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Generate_Button.setGeometry(QtCore.QRect(170, 260, 151, 31))
        self.Generate_Button.setObjectName("Generate_Button")
        self.Reset_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_Button.setGeometry(QtCore.QRect(170, 230, 151, 31))
        self.Reset_Button.setObjectName("Reset_Button")
        self.rests_chb = QtWidgets.QCheckBox(self.centralwidget)
        self.rests_chb.setGeometry(QtCore.QRect(20, 290, 87, 20))
        self.rests_chb.setObjectName("rests_chb")
        self.div_chb = QtWidgets.QCheckBox(self.centralwidget)
        self.div_chb.setEnabled(True)
        self.div_chb.setGeometry(QtCore.QRect(170, 200, 131, 20))
        self.div_chb.setObjectName("div_chb")
        self.unreg_chb = QtWidgets.QCheckBox(self.centralwidget)
        self.unreg_chb.setEnabled(True)
        self.unreg_chb.setGeometry(QtCore.QRect(170, 170, 87, 20))
        self.unreg_chb.setChecked(False)
        self.unreg_chb.setAutoRepeat(False)
        self.unreg_chb.setTristate(False)
        self.unreg_chb.setObjectName("unreg_chb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.rests_chb.clicked['bool'].connect(self.groupBox_4.setEnabled)
        self.div_chb.clicked['bool'].connect(self.groupBox_2.setEnabled)
        self.unreg_chb.clicked['bool'].connect(self.groupBox_3.setEnabled)
        self.Reset_Button.clicked.connect(self.measure_line.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Regular Rhythm Manager"))
        self.groupBox.setTitle(_translate("MainWindow", "Main"))
        self.dur_cb.setItemText(0, _translate("MainWindow", "1/16"))
        self.dur_cb.setItemText(1, _translate("MainWindow", "1/8"))
        self.dur_cb.setItemText(2, _translate("MainWindow", "1/4"))
        self.dur_cb.setItemText(3, _translate("MainWindow", "1/2"))
        self.dur_cb.setItemText(4, _translate("MainWindow", "1/16 Trippled"))
        self.dur_cb.setItemText(5, _translate("MainWindow", "1/8 Trippled"))
        self.dur_cb.setItemText(6, _translate("MainWindow", "1/4 Trippled"))
        self.dur_cb.setItemText(7, _translate("MainWindow", "1/2 Trippled"))
        self.label.setText(_translate("MainWindow", "Duration:"))
        self.label_2.setText(_translate("MainWindow", "Measure:"))
        self.label_6.setText(_translate("MainWindow", "Number of tacts:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Division"))
        self.label_3.setText(_translate("MainWindow", "Division percentage:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Special"))
        self.label_4.setText(_translate("MainWindow", "By parts:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rests"))
        self.label_5.setText(_translate("MainWindow", "Rests percentage:"))
        self.Generate_Button.setText(_translate("MainWindow", "Generate"))
        self.Reset_Button.setText(_translate("MainWindow", "Reset"))
        self.rests_chb.setText(_translate("MainWindow", "Add rests"))
        self.div_chb.setText(_translate("MainWindow", "Divide main beats"))
        self.unreg_chb.setText(_translate("MainWindow", "Unregular"))
